### ISSUE TITLE
Change a server port from 50209 to 50210

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#18] opened 2018-04-04 23:27 UTC
Hi Alan, not sure if I have to use this channel to give a suggestion....sorry in case not.

I would like to suggest you to change the server port of file s2m_http_server.py from **50209** to **50210**.
That will be nice in case a user want to combine extensions (Arduino and micro:bit).
So an Arduino can communicate to micro:bit via Scratch and vice versa.
I have changed my local file and worked fine for this purpose.
Thanks!

**Comment by MrYsLab** [comment] 2018-04-05 12:30
Hi Edson, posting here is appropriate. Can you please give me some more detail how about this works?
What I am asking is, is there a single instance of Scratch controlling both the Arduino and the micro:bit or 2 separate instances?
What is the mechanism for both boards to communicate with each other? 
Thanks

**Comment by sobreira** [comment] 2018-04-06 01:45
Hi Alan, I have already combined 3 Strach extenstions S2aio and S2m and ScratcherControl (Android).
As I changed the port in my local file 50209 for S2aio and 50210 for S2m, I can have a single instance of Scratch and I can connect Arduino and S2m at the same time.
Following one example about micro:bit sending data to Scratch and change the Servo position:
(sorry to be in pt-br)

![image](https://user-images.githubusercontent.com/5200448/38399784-da2dcefc-3922-11e8-8e90-6a1b4ad7ed69.png)

Thanks!

**Comment by MrYsLab** [comment] 2018-04-07 14:03
Ok, I now see how you did it. I am not going to change the port number because if I do, if some users have saved their Scratch projects and try to run them again, they will not work. I will be leaving things as is. Also, I do not how I would bring up everything automatically for users that want both Arduino and micro:bit.

I am closing this issue, but if you have any other questions, you can post them here and I will see them even though the issue is closed.

**Closed as completed by MrYsLab** 2018-04-07 14:03 UTC
Labels: enhancement
