### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by Githubmoses** [MrYsLab/s2m#32] opened 2018-09-10 05:32 UTC
I had no trouble installing this on a Windows 7 machine, but the s2m blocks never appeared in Scratch.  I tried on a Windows 10 machine and everything seems fine until I tried running s2m.  I get these errors: 

s2m version 2.11 Copyright(C) 2018 Alan Yorinks  All rights reserved.

Python Version 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
Autodetecting serial port. Please wait...
Using COM Port:com4

s2mb Version: s2mb.py Version 1.10 14 April 2018

Auto launching Scratch
Traceback (most recent call last):
  File "c:\program files\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37-32\Scripts\s2m.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37-32\lib\site-packages\s2m\s2m.py", line 617, in main
    base_path=user_base_path, display_base_path=display, language=lang)
  File "c:\program files\python37-32\lib\site-packages\s2m\s2m.py", line 235, in __init__
    self.auto_load_scratch()
  File "c:\program files\python37-32\lib\site-packages\s2m\s2m.py", line 342, in auto_load_scratch
    scratch_proc = Popen(exec_string, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
  File "c:\program files\python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

ANY SUGGESTIONS??

**Comment by Githubmoses** [comment] 2018-09-10 05:40
I forgot to mention that I have checked the files; they exist. The initial installation had a capital L in the "lib" directory.  I changed it in case there was a case sensitive issue.  Didn't help.  Then check those lines in the .py files and they refer to preset user directories and junk.  I am not smart enough to know what the problem is so anything anyone can point me to would be great.  : )

**Comment by MrYsLab** [comment] 2018-09-10 09:38
Could you please run s2m with the -d option set to true and copy and paste the command window output here? The command should look similar to this:
```
s2m -d true
```

**Comment by MrYsLab** [comment] 2018-09-10 12:54
The issue you are having is that s2m that it is not able to open Scratch. Here are the things to check:
1. Go into C:/Program Files (x86)/Scratch 2 and make sure that Scratch 2.exe exists.
![image](https://user-images.githubusercontent.com/5189838/45298605-06367280-b4d7-11e8-9faa-32af35a18a2c.png)
2. After running s2m -d true, go into the directory shown in the Python path string:
![image](https://user-images.githubusercontent.com/5189838/45298399-5f51d680-b4d6-11e8-9c72-def8e42b2138.png)
3. Go into that directory. Here are the files you should see:
![screenshot from 2018-09-10 08-36-40](https://user-images.githubusercontent.com/5189838/45298464-945e2900-b4d6-11e8-986c-5799cf23bb60.png)
4. Then go into the scratch_files/projects directory and make sure that s2m.sb2 is there. If you are using a language other English, then make sure you an .sb2 file for your language is shown.
![screenshot from 2018-09-10 08-44-52](https://user-images.githubusercontent.com/5189838/45298527-c66f8b00-b4d6-11e8-9eb2-a0ed85b353b0.png)

Please let me know if all the files are  correctly in place.

**Comment by MrYsLab** [comment] 2018-09-10 12:57
You can also try starting the program manually. The instructions to do so are [located here.](https://mryslab.github.io/s2m/usage/#manually-starting-s2m-and-scratch)

**Comment by Githubmoses** [comment] 2018-09-10 20:22
You area genius.  What happened was Scratch 2 was installed into Program Files sans (x86).  I uninstalled, and reinstalled into that direectory and it runs.  However, I am having the same problem as on the windows 7 machine: everything seems to  be working fine except that the blocks do not show up after the command "s2m" fires up Scratch.  It all seems to work properly but the "More Blocks options produces nothing.  It shows just the usual "Make a Block" and "Add and Extension" buttons.  Any thoughts?  This happens on my Win7 and Win10 machines.

**Comment by MrYsLab** [comment] 2018-09-10 21:03
If you follow steps 2 through 4 above, do you see the .sb2 files on your computer? If you do, you can try and manually load a project from Scratch after s2m starts Scratch. Click on File and select Load from the menu at the top of Scratch. It will bring up a file explorer window. Using the path printed by the s2m -d true command, you will need to select a .sb2 file to load. The file s2m.sb2 is the file for the blocks to be shown in English. 

If you do this, do the blocks now appear?



![image](https://user-images.githubusercontent.com/5189838/45324031-ffc9ea00-b51a-11e8-88fa-35bff30cf2fe.png)

**Comment by Githubmoses** [comment] 2018-09-10 21:24
Yes.  All the files are in the right places.  Manually loaded s2m.sb2 thru Scratch after it was opened with s2m command, and it works like a charm. You're amazing.  Thank you so much for taking the time to help me.

**Comment by MrYsLab** [comment] 2018-09-10 22:43
You shouldn't have to go through all of this to get things running. A possible simpler workaround is to first start Scratch and after it is up, then start s2m.  Please let me know if that works for you. 

I can't understand why things are behaving the way they are for you. I have not had any other reports of this type of behavior. One other thing you can try, just to see if Scratch is accepting command line arguments on your computer is to type is the following in a command window without running s2m:
```
"c:\program files (x86)\scratch 2\scratch 2.exe" c:\users\alan\appdata\local\programs\python\python37\lib\site-packages\s2m\scratch_files\projects\s2m.sb2"
```
Just change the c:\users\alan portion to be whatever you the path is for your computer. The blocks should come up, but the connectivity indicator should be red and not green. If you do not see the blocks, then the problem is within Scratch. If they do come up, then I am stumped. The line above is constructed within s2m and used to execute Scratch from within.

**Comment by Githubmoses** [comment] 2018-09-11 00:59
Opening scratch and then starting up s2m from command line does not yield different results.  I copy and pasted your command line example above.  It opens scratch but again, the buttons are not under "More Blocks."  But, again, if I load the file from it's original location, the same one used in the command line argument, they show up and work fine.  I have no idea why this is doing what it's doing either.  But the work around, for me, is okay too.  I've put a shortcut on my desktop and open that file when I want to work with the Microbit.  I will tell you that we also use S2Bot for the WeDo and it has similar functionality where you click a button from the app and it auto opens the template file that includes the buttons under "More Blocks", and that works fine.  If there's something else I can do to help you trouble shoot what is happening in this particular case, I am glad to help. But the work around is okay too.  I'm just thrilled that it's working.  I'm teaching homeschool kids to code and they love it!

**Comment by MrYsLab** [comment] 2018-09-11 15:14
Since the command line example does not work, it points to a Scratch issue. In that example, the first part of the command points to and starts Scratch, and the second part passes a path and a Scratch project file that Scratch should and load upon starting. At this point, it is probably not worth chasing down since you have an acceptable workaround. Perhaps you accept all of the defaults values for both Scratch and Adobe AIR when installing Scratch or not. It is also possible, that there is something in your Windows environment causing the issue. Again, it is probably not worth the effort to chase this down.
Since this is not an s2m issue, I will close the issue. Please feel free to post a comment here if you feel it should be reopened, or if you encounter any other issues, just enter a new issue.
Thanks
Alan

**Closed as completed by MrYsLab** 2018-09-11 15:14 UTC
