### ISSUE TITLE
Radio Option

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#19] opened 2018-04-05 01:43 UTC
Hi, Alan, 
According to your experience, do you think is feasible to use Scratch to send and receive radio command to/from another micro:bit in a properly way, as BLE is not available in micropython?)

In this way should be possible to:

- Scratch + usb connected micro:bit to control a remote micro:bit

- Remote micro:bit to send command - to an usb connected micro:bit + Scratch - like (button A pressed, button B pressed , tilt up, tilt down, right, etc...) so they can control sprites remotelly.
 
I have changed your program, to make an experiement, but I realized that when I send commands to remote micro:bit, looks that Scratch broadcasts it several times - not sure if exist and effective way for debounce it, I have used wait in Scratch, but not sure if there is a collateral effect.

What I did was:
Got file s2mb.py
Included:
```
import radio
import random
radio.on()
```
replaced  `display.scroll(str(cmd_list[1]), wait=False)` to `radio.send(cmd_list[1])` so I could use your scroll command to send any code via radio using and existent block).

The receiver micro:bit I flashed with the following code:
```
import radio
import random
from  microbit import display

radio.on()
while True:

    incoming = radio.receive()
    if incoming == 'a':
        display.scroll("a")
    if incoming == 'b':
        display.scroll("b")
    if incoming == 'c':
        display.scroll("c")
```
At the Scratch side I have used:
![image](https://user-images.githubusercontent.com/5200448/38342617-ed858364-3855-11e8-9f4d-78decad9ec33.png)

I think Scratch sending to remote micro:bit should be possible (at least worked), but I have no idea on the other way around (which makes the thing much better) and also if is possible to define a radio signal in order to avoid send the same commmand to all micro:bit.

Thanks!

**Comment by MrYsLab** [comment] 2018-04-05 12:48
I am not sure if you have seen my [microbit-robot project](https://mryslab.github.io/microbit-robot/), but I am using the radio function to control the robot. In fact, I present [4 different types of remote controllers](https://mryslab.github.io/microbit-robot/controllers/) in the project.
This project does not display any data from the robot, but it should not be difficult to do. The only issue is if there is enough programming room left on the micro:bit computers to do so.

To debounce a button press, you might try putting a wait block in each if block.

To associate each micro:bit with a single instance of Scratch, one could use [radio addressing](http://microbit-micropython.readthedocs.io/en/latest/tutorials/radio.html#addressing).

That would mean that more blocks would have to be added to support radio addressing. This would be more work for an instructor to assign addresses and to make sure they were entered correctly.

Also, I know with the BLE feature (not Python), where there are several micro:bits in a single room, things do not work very will - they interfere with each other. I am not sure if you had a classroom full of micro:bits that the radio functions would not also have issues of intererence.

In any case, this would be a lot of work, and I don't know how many teachers would use it, since it adds more work from them.

**Comment by sobreira** [comment] 2018-04-06 01:27
Ok, I got it, I will have a look on this.
Thank you very much.

As I am not so familiar with Python.
Is there a way, once conection is stabilished to get the Scratch data (sent and received) (like a MsgBox to popup or a serial monitor, etc...) for debuggin purposes?
Same thing for micro:bit sending and receiving data.
Just to see the content and maybe parsing the variable if needed.

Thanks!

**Comment by MrYsLab** [comment] 2018-04-07 13:59
Unfortunately, the Scratch files do not provide any way to debug. For the micro:bit, the way I debug the script on the micro:bit, is to open up the serial terminal on the Arduino IDE and use that to both send data to the micro:bit and to see what it sends back. Very primitive and painful, but it is better than nothing.

I am going to close this issue, since I will not be adding the feature because it will add a lot of complexity. If you have any other questions, you can add them here even though the issue is closed and I will still see it.

**Closed as completed by MrYsLab** 2018-04-07 13:59 UTC
Labels: enhancement
